# Generated by Django 2.2.5 on 2019-09-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dlp', '0002_filterrule_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DLPDetection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Text of the message')),
                ('event_source', models.TextField(help_text='JSON string with slack event')),
                ('dlp_rule', models.ForeignKey(help_text='DLP rule that caught the message', null=True, on_delete=django.db.models.deletion.SET_NULL, to='dlp.FilterRule')),
            ],
        ),
    ]
