# Generated by Django 2.2.5 on 2019-09-05 13:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slack_connector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlpdetection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
