# Generated by Django 2.2.5 on 2019-09-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterrule',
            name='description',
            field=models.TextField(blank=True, help_text='You can put verbose description of the rule here'),
        ),
    ]
